### ISSUE TITLE
Salut toi, on se connaît ? :)

### ISSUE THREAD

**Issue by Crysicia** [Paul-Thorel/Paul-Thorel.github.io#1]
Je crois qu'on se connaît, mais je ne suis pas très sûr de moi sur ce coup...

**Comment by Paul-Thorel** [comment]
Mais chut , ici c'est réservé aux issues ;) .

**Comment by Crysicia** [comment]
Hum... Comment m'as-tu trouvé ? :p

**Comment by Paul-Thorel** [comment]
paulthorel.pro@gmail.com , ;) , normalement c'est la bonne ( Je gère au moins 10 mails ) :)

**Comment by Crysicia** [comment]
Sent !
